

export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description: "Get inerview questions and model answers based on your role, experience and specific focues areas, no generic practice here"
    },
    {
        id: "02",
        title: "Learn at your own pace",
        description: "Expand answers only when you are ready. Dive deeper into any concept istantly with AI-powered detailed explanations"
    },
    {
        id:"03",
        title: "Capture Your Insights",
        description: "Add personal notes to any question and pin important ones to the top - making your learning more organised and impactful"
    },
    {
        id:"04",
        title: 'Understand the "Why?" Behind Answers',
        description: "Beyond just answers- unlock detailed concept explanations generated by AI, helping you trule master each topic"
    },
    {
        id: "05",
        title: "Save, Organize, and Revisit",
        description: "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off."
    },
];